[tool.poetry]
name = "ytm-playlist-manager"
version = "0.1.0"
description = ""
authors = ["Mario Knapp <knappmk@informatik.uni-marburg.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ytmusicapi = "==1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
